version: '3.8'

services:
  db:
    image: postgres:16
    container_name: trackcore-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: maggot14
      POSTGRES_DB: trackcore
    ports:
      - "5432:5432"
    volumes:
      - trackcore-data:/var/lib/postgresql/data
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  backend:
    build: ./backend-java
    container_name: trackcore-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/trackcore
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: maggot14
    depends_on:
      - db

volumes:
  trackcore-data: